In [1]:
import torch

inputs = torch.tensor(
  [[ 1.9269,  1.4873, -0.4974],
    [ 0.4396, -0.7581,  1.0783],
    [ 0.8008,  1.6806,  0.3559],
    [-0.6866,  0.6105,  1.3347],
    [-0.2316,  0.0418, -0.2516],
    [ 0.8599, -0.3097, -0.3957]]
)

In [2]:
x_2 = inputs[1]
d_out = 2
d_in = inputs.shape[1]

In [3]:
torch.manual_seed(42)
Wq = torch.nn.Linear(d_in,d_out,bias = False)
Wk = torch.nn.Linear(d_in,d_out,bias = False)
Wv = torch.nn.Linear(d_in,d_out,bias = False)

In [4]:
print(Wq.weight)

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353],
        [ 0.5304, -0.1265,  0.1165]], requires_grad=True)


In [5]:
print(Wk.weight)

Parameter containing:
tensor([[-0.2811,  0.3391,  0.5090],
        [-0.4236,  0.5018,  0.1081]], requires_grad=True)


In [6]:
print(Wv.weight)

Parameter containing:
tensor([[ 0.4266,  0.0782,  0.2784],
        [-0.0815,  0.4451,  0.0853]], requires_grad=True)


In [7]:
print(x_2.shape)
print(Wq.weight.shape)

torch.Size([3])
torch.Size([2, 3])


In [8]:
query_2 = x_2 @ Wq.weight.T
key_2 = x_2 @ Wk.weight.T
value_2 = x_2 @ Wv.weight.T
print(query_2)

tensor([-0.3151,  0.4547], grad_fn=<SqueezeBackward4>)


In [9]:
keys = inputs @ Wk.weight.T
queries = inputs @ Wq.weight.T
values = inputs @ Wv.weight.T

In [10]:
inputs

tensor([[ 1.9269,  1.4873, -0.4974],
        [ 0.4396, -0.7581,  1.0783],
        [ 0.8008,  1.6806,  0.3559],
        [-0.6866,  0.6105,  1.3347],
        [-0.2316,  0.0418, -0.2516],
        [ 0.8599, -0.3097, -0.3957]])

In [11]:
print(Wq.weight.T)
print(Wk.weight.T)
print(Wv.weight.T)

tensor([[ 0.4414,  0.5304],
        [ 0.4792, -0.1265],
        [-0.1353,  0.1165]], grad_fn=<PermuteBackward0>)
tensor([[-0.2811, -0.4236],
        [ 0.3391,  0.5018],
        [ 0.5090,  0.1081]], grad_fn=<PermuteBackward0>)
tensor([[ 0.4266, -0.0815],
        [ 0.0782,  0.4451],
        [ 0.2784,  0.0853]], grad_fn=<PermuteBackward0>)


In [12]:
keys

tensor([[-0.2905, -0.1235],
        [ 0.1682, -0.4501],
        [ 0.5259,  0.5426],
        [ 1.0793,  0.7414],
        [-0.0488,  0.0919],
        [-0.5481, -0.5624]], grad_fn=<MmBackward0>)

In [13]:
queries

tensor([[ 1.6305,  0.7759],
        [-0.3151,  0.4547],
        [ 1.1107,  0.2536],
        [-0.1910, -0.2859],
        [-0.0482, -0.1574],
        [ 0.2847,  0.4491]], grad_fn=<MmBackward0>)

In [14]:
values

tensor([[ 0.7997,  0.4624],
        [ 0.4284, -0.2812],
        [ 0.5721,  0.7131],
        [ 0.1264,  0.4416],
        [-0.1656,  0.0160],
        [ 0.2324, -0.2417]], grad_fn=<MmBackward0>)

In [15]:
key_2 = keys[1]
attn_score_22 = query_2.dot(key_2)
attn_score_22

tensor(-0.2577, grad_fn=<DotBackward0>)